export const CONTACTS_GET_DATA = 'CONTACTS_GET_DATA';
export const CONTACTS_GET_DATA_SUCCESS = 'CONTACTS_GET_DATA_SUCCESS';
export const CONTACTS_GET_ONE_CONTACT = 'CONTACTS_GET_ONE_CONTACT';
export const CONTACTS_GET_ONE_CONTACT_SUCCESS = 'CONTACTS_GET_ONE_CONTACT_SUCCESS';
export const CONTACTS_PUT_CONTACT = 'CONTACTS_PUT_CONTACT';
export const CONTACTS_PUT_CONTACT_SUCCESS = 'CONTACTS_PUT_CONTACT_SUCCESS';
export const CONTACTS_ADD_CONTACT = 'CONTACTS_ADD_CONTACT';
export const CONTACTS_ADD_CONTACT_SUCCESS = 'CONTACTS_ADD_CONTACT_SUCCESS';
export const CONTACTS_DELETE_CONTACT = 'CONTACTS_DELETE_CONTACT';
export const CONTACTS_DELETE_CONTACT_SUCCESS = 'CONTACTS_DELETE_CONTACT_SUCCESS';


