export const FETCH_DASHBOARD_DATA = 'FETCH_DASHBOARD_DATA';
export const FETCH_DASHBOARD_DATA_SUCCESS = 'FETCH_DASHBOARD_DATA_SUCCESS';
export const FETCH_DASHBOARD_DATA_BOOKING = 'FETCH_DASHBOARD_DATA_BOOKING';
export const FETCH_DASHBOARD_DATA_BOOKING_SUCCESS = 'FETCH_DASHBOARD_DATA_BOOKING_SUCCESS';
export const FETCH_DASHBOARD_DATA_PREBOOKED = 'FETCH_DASHBOARD_DATA_PREBOOKED';
export const FETCH_DASHBOARD_DATA_PREBOOKED_SUCCESS = 'FETCH_DASHBOARD_DATA_PREBOOKED_SUCCESS';
export const FETCH_DASHBOARD_DATA_TRANSIT = 'FETCH_DASHBOARD_DATA_TRANSIT';
export const FETCH_DASHBOARD_DATA_TRANSIT_SUCCESS = 'FETCH_DASHBOARD_DATA_TRANSIT_SUCCESS';
export const FETCH_DASHBOARD_DATA_DELIVERED = 'FETCH_DASHBOARD_DATA_DELIVERED';
export const FETCH_DASHBOARD_DATA_DELIVERED_SUCCESS = 'FETCH_DASHBOARD_DATA_DELIVERED_SUCCESS';

