export const FLASH_SUCCESS = 'FLASH_SUCCESS';
export const FLASH_ERROR = 'FLASH_ERROR';
export const FLASH_RESET = 'FLASH_RESET';
export const SHOW_NOTIFICATION_UPDATED = 'SHOW_NOTIFICATION_UPDATED';
