export const SEARCH_QUOTES = 'SEARCH_QUOTES';
export const SEARCH_QUOTES_RESET = 'SEARCH_QUOTES_RESET';
export const SEARCH_QUOTES_SUCCESS = 'SEARCH_QUOTES_SUCCESS';
export const SEARCH_QUOTES_ERROR = 'SEARCH_QUOTES_ERROR';
export const SEARCH_QUOTES_SORT = 'SEARCH_QUOTES_SORT';
