export const SEARCH_QUOTES_BOOKING = 'SEARCH_QUOTES_BOOKING';
export const SEARCH_QUOTES_BOOKING_SUCCESS = 'SEARCH_QUOTES_BOOKING_SUCCESS';
export const SEARCH_QUOTES_BOOKING_RESET = 'SEARCH_QUOTES_BOOKING_RESET';
