export const SHIPMENT_OVERVIEW_GET_DATA = 'SHIPMENT_OVERVIEW_GET_DATA';
export const SHIPMENT_OVERVIEW_GET_DATA_SUCCESS = 'SHIPMENT_OVERVIEW_GET_DATA_SUCCESS';
export const SUBMIT_SHIPMENT_OVERVIEW_DATA = 'SUBMIT_SHIPMENT_OVERVIEW_DATA';
export const SUBMIT_SHIPMENT_OVERVIEW_DATA_SUCCESS = 'SUBMIT_SHIPMENT_OVERVIEW_DATA_SUCCESS';
export const SHIPMENT_OVERVIEW_UNPIN_MESSAGE = 'SHIPMENT_OVERVIEW_UNPIN_MESSAGE';
export const SHIPMENT_OVERVIEW_UNPIN_MESSAGE_SUCCESS = 'SHIPMENT_OVERVIEW_UNPIN_MESSAGE_SUCCESS';
