export const SHIPMENT_LAYOUT_GET_DATA = 'SHIPMENT_LAYOUT_GET_DATA';
export const SHIPMENT_LAYOUT_GET_DATA_SUCCESS = 'SHIPMENT_LAYOUT_GET_DATA_SUCCESS';
export const SHIPMENT_LAYOUT_DELETE_SHIPMENT = 'SHIPMENT_LAYOUT_DELETE_SHIPMENT';
export const SHIPMENT_LAYOUT_DELETE_SHIPMENT_SUCCESS = 'SHIPMENT_LAYOUT_DELETE_SHIPMENT_SUCCESS';
export const SHIPMENT_LAYOUT_ACCEPT_QUOTE = 'SHIPMENT_LAYOUT_ACCEPT_QUOTE';
export const SHIPMENT_LAYOUT_ACCEPT_QUOTE_SUCCESS = 'SHIPMENT_LAYOUT_ACCEPT_QUOTE_SUCCESS';

