export const SHIPMENTS_GET_DATA = 'SHIPMENTS_GET_DATA';

export const SHIPMENTS_GET_DATA_SUCCESS = 'SHIPMENTS_GET_DATA_SUCCESS';

export const SHIPMENTS_GET_DATA_AND_FILTERS = 'SHIPMENTS_GET_DATA_AND_FILTERS';

export const SHIPMENTS_GET_DATA_AND_FILTERS_SUCCESS = 'SHIPMENTS_GET_DATA_SUCCESS_AND_FILTERS_SUCCESS';

export const SHIPMENTS_DOWNLOAD_EXCEL = 'SHIPMENTS_DOWNLOAD_EXCEL';
