version: "3"
services:
  server:
    build:
      context: .
    image: lotto-mansion-server
    container_name: lotto-mansion-server
    working_dir: /app
    expose:
      - 8080
    depends_on:
      - postgres
    volumes:
      - ./data/server/share:/share

  postgres:
    image: postgres:10.4
    container_name: lotto-mansion-db
    env_file:
      - .env
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
      - ./data/postgres/share:/share
